[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.4.0"

[[constraint]]
  name = "github.com/valyala/fasthttp"
  version = "20180529.0.0"
